// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Peladas_WEBAPI.Data;

namespace Peladas_WEBAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220223000600_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Peladas_WEBAPI.Models.Agendamento", b =>
                {
                    b.Property<int>("usuarioId")
                        .HasColumnType("int");

                    b.Property<int>("peladaId")
                        .HasColumnType("int");

                    b.HasKey("usuarioId", "peladaId");

                    b.HasIndex("peladaId");

                    b.ToTable("Agendamentos");

                    b.HasData(
                        new
                        {
                            usuarioId = 1,
                            peladaId = 1
                        },
                        new
                        {
                            usuarioId = 2,
                            peladaId = 2
                        },
                        new
                        {
                            usuarioId = 3,
                            peladaId = 3
                        },
                        new
                        {
                            usuarioId = 4,
                            peladaId = 4
                        },
                        new
                        {
                            usuarioId = 5,
                            peladaId = 5
                        },
                        new
                        {
                            usuarioId = 1,
                            peladaId = 3
                        },
                        new
                        {
                            usuarioId = 3,
                            peladaId = 2
                        });
                });

            modelBuilder.Entity("Peladas_WEBAPI.Models.LocalP", b =>
                {
                    b.Property<int>("localPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apelido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeLocal")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("localPId");

                    b.ToTable("LocaisP");

                    b.HasData(
                        new
                        {
                            localPId = 1,
                            apelido = "Renato Russo",
                            nomeLocal = "Ginásio Renato Manfredini"
                        },
                        new
                        {
                            localPId = 2,
                            apelido = "Cazuzão",
                            nomeLocal = "Ginásio Agenor Miranda"
                        },
                        new
                        {
                            localPId = 3,
                            apelido = "Leoni",
                            nomeLocal = "Quadra Carlos Leoni"
                        },
                        new
                        {
                            localPId = 4,
                            apelido = "Frejat",
                            nomeLocal = "Quadra Roberto Frejat"
                        },
                        new
                        {
                            localPId = 5,
                            apelido = "PR",
                            nomeLocal = "Campo Síntético Paulo Ricardo"
                        });
                });

            modelBuilder.Entity("Peladas_WEBAPI.Models.Pelada", b =>
                {
                    b.Property<int>("peladaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dataAgend")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dataEvento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("horaEvento")
                        .HasColumnType("datetime2");

                    b.Property<int>("localPId")
                        .HasColumnType("int");

                    b.Property<string>("nomeEvento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("peladaId");

                    b.HasIndex("localPId");

                    b.ToTable("Peladas");

                    b.HasData(
                        new
                        {
                            peladaId = 1,
                            dataAgend = new DateTime(2022, 2, 22, 21, 6, 0, 522, DateTimeKind.Local).AddTicks(7584),
                            dataEvento = new DateTime(2022, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            horaEvento = new DateTime(2022, 2, 22, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            localPId = 1,
                            nomeEvento = "Grupo Ypiranga"
                        },
                        new
                        {
                            peladaId = 2,
                            dataAgend = new DateTime(2022, 2, 22, 21, 6, 0, 525, DateTimeKind.Local).AddTicks(6726),
                            dataEvento = new DateTime(2022, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            horaEvento = new DateTime(2022, 2, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            localPId = 2,
                            nomeEvento = "Grupo Bahia"
                        },
                        new
                        {
                            peladaId = 3,
                            dataAgend = new DateTime(2022, 2, 22, 21, 6, 0, 525, DateTimeKind.Local).AddTicks(6812),
                            dataEvento = new DateTime(2022, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            horaEvento = new DateTime(2022, 2, 22, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            localPId = 3,
                            nomeEvento = "Grupo Vitória"
                        },
                        new
                        {
                            peladaId = 4,
                            dataAgend = new DateTime(2022, 2, 22, 21, 6, 0, 525, DateTimeKind.Local).AddTicks(6822),
                            dataEvento = new DateTime(2022, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            horaEvento = new DateTime(2022, 2, 22, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            localPId = 4,
                            nomeEvento = "Grupo Botafogo SSA"
                        },
                        new
                        {
                            peladaId = 5,
                            dataAgend = new DateTime(2022, 2, 22, 21, 6, 0, 525, DateTimeKind.Local).AddTicks(6829),
                            dataEvento = new DateTime(2022, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            horaEvento = new DateTime(2022, 2, 22, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            localPId = 5,
                            nomeEvento = "Grupo Leônico"
                        },
                        new
                        {
                            peladaId = 6,
                            dataAgend = new DateTime(2022, 2, 22, 21, 6, 0, 525, DateTimeKind.Local).AddTicks(6838),
                            dataEvento = new DateTime(2022, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            horaEvento = new DateTime(2022, 2, 22, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            localPId = 2,
                            nomeEvento = "Grupo Galícia"
                        },
                        new
                        {
                            peladaId = 7,
                            dataAgend = new DateTime(2022, 2, 22, 21, 6, 0, 525, DateTimeKind.Local).AddTicks(6845),
                            dataEvento = new DateTime(2022, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            horaEvento = new DateTime(2022, 2, 22, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            localPId = 3,
                            nomeEvento = "Grupo Cruzeiro do Sul"
                        });
                });

            modelBuilder.Entity("Peladas_WEBAPI.Models.Usuario", b =>
                {
                    b.Property<int>("usuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apelido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("senha")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("usuarioId");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            usuarioId = 1,
                            apelido = "Táta",
                            email = "tata@gmail.com",
                            nomeCompleto = "Marta Antunes",
                            senha = "prodeb"
                        },
                        new
                        {
                            usuarioId = 2,
                            apelido = "Paulinha",
                            email = "Paulinha@gmail.com",
                            nomeCompleto = "Paula Nascimento",
                            senha = "prodeb"
                        },
                        new
                        {
                            usuarioId = 3,
                            apelido = "Laurinha",
                            email = "tata@gmail.com",
                            nomeCompleto = "Laura Barros",
                            senha = "prodeb"
                        },
                        new
                        {
                            usuarioId = 4,
                            apelido = "Lúh",
                            email = "luh@gmail.com",
                            nomeCompleto = "Luiza Santiago",
                            senha = "prodeb"
                        },
                        new
                        {
                            usuarioId = 5,
                            apelido = "Kazão",
                            email = "kazao@gmail.com",
                            nomeCompleto = "Lucas Ferreira",
                            senha = "prodeb"
                        },
                        new
                        {
                            usuarioId = 6,
                            apelido = "Pedroca",
                            email = "droca@gmail.com",
                            nomeCompleto = "Pedro Silva",
                            senha = "prodeb"
                        },
                        new
                        {
                            usuarioId = 7,
                            apelido = "Paulito",
                            email = "lito@gmail.com",
                            nomeCompleto = "Paulo Santos",
                            senha = "prodeb"
                        });
                });

            modelBuilder.Entity("Peladas_WEBAPI.Models.Agendamento", b =>
                {
                    b.HasOne("Peladas_WEBAPI.Models.Pelada", "Pelada")
                        .WithMany("Agendamentos")
                        .HasForeignKey("peladaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peladas_WEBAPI.Models.Usuario", "Usuario")
                        .WithMany("Agendamentos")
                        .HasForeignKey("usuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Peladas_WEBAPI.Models.Pelada", b =>
                {
                    b.HasOne("Peladas_WEBAPI.Models.LocalP", "LocalP")
                        .WithMany()
                        .HasForeignKey("localPId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
